services:
  app:
    image: php:8.1-cli
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DOCKER_ENV=true
      - PHP_DISPLAY_ERRORS=1
    command: >
      bash -c "
        mkdir -p /app/app/logs &&
        chmod -R 777 /app/app/logs &&
        php -S 0.0.0.0:8000 docker-router.php
      "
    restart: unless-stopped 